# Basic
title: Jett's Blog
author: jett
description: iOS developer

url: "https://mutating.github.io"
permalink: /:year/:month/:title/

# Conversion
markdown:    kramdown
highlighter: rouge

# Pagination
gems: [jekyll-paginate]
paginate: 9
paginate_path: "pages/:num/"

# Social
social:
  mail: ma.jiangtao@foxmail.com
  github: mutating

# Resource
assets:
  base: https://github.com/mutating/mutating.github.io
  resources: https://github.com/mutating/mutating.github.io/resources